export type LifecycleEventLM = {
  eventId: string;
  holdingId: string;
  accountId: string;
  clientId: string;
  eventDate: string;
  cusip: string;
  isin: string;
  issuer: string;
  structureType: string;
  eventType: string;
  couponRatePercent: number;
  markToMarketPercent: number;
  basketType: string;
  underlierPerformancePercent: number;
  listOfUnderliers: string[];
  activeUnderlier: string;
  activeUnderlierLevel: number;
  protectionProximityLevelPercent: number;
  protectionLevelPercent: number;
  protectionType: string;
  eventProximityPercent: number;
  eventProximityIndicator: string;
  eventLevelPercent: number;
  notionalHoldingsSum: number;
  intrinsicValue: number;
  payoutAmount: number;
};

export const mockLifecycleEventData: LifecycleEventLM[] = [
  {
    eventId: '1',
    holdingId: '1',
    accountId: '32454',
    clientId: '45673',
    eventDate: '2022-09-02',
    cusip: 'XS2418730300',
    isin: 'XS2418730300',
    issuer: 'UBS AG Jersey Branch',
    structureType: 'Crypto Autocall',
    eventType: 'Coupon Payment Date',
    couponRatePercent: 0.75,
    markToMarketPercent: 91.30363,
    basketType: 'Single',
    underlierPerformancePercent: -85,
    listOfUnderliers: ['ETH', 'BTC', 'LUNA', 'ALGO', 'SHIB'],
    activeUnderlier: 'BTC',
    activeUnderlierLevel: 94,
    protectionProximityLevelPercent: -5.7,
    protectionLevelPercent: 75.5,
    protectionType: 'Barrier',
    eventProximityPercent: 42,
    eventProximityIndicator: 'Above',
    eventLevelPercent: 45,
    notionalHoldingsSum: 2000000,
    intrinsicValue: 10000000,
    payoutAmount: 4000,
  },
  {
    eventId: '2',
    holdingId: '2',
    accountId: '39954',
    clientId: '45673',
    eventDate: '2022-10-12',
    cusip: 'XS2418730300',
    isin: 'XS2418730300',
    issuer: 'UBS AG Jersey Branch',
    structureType: 'Autocall',
    eventType: 'Coupon Evaluation Date',
    couponRatePercent: 0.7,
    markToMarketPercent: 65.34863,
    basketType: 'Single',
    underlierPerformancePercent: -85,
    listOfUnderliers: ['BTC', 'GME', 'BBY'],
    activeUnderlier: 'GME',
    activeUnderlierLevel: 90,
    protectionProximityLevelPercent: 6.4,
    protectionLevelPercent: 70.5,
    protectionType: 'Barrier',
    eventProximityPercent: 39,
    eventProximityIndicator: 'Above',
    eventLevelPercent: 45,
    notionalHoldingsSum: 4320.53,
    intrinsicValue: 14000000,
    payoutAmount: 5000,
  },
  {
    eventId: '3',
    holdingId: '3',
    accountId: '20954',
    clientId: '45673',
    eventDate: '2022-10-12',
    cusip: '48133CQU9',
    isin: '48133CQU9',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'China Stock Autocall',
    eventType: 'Coupon Payment Date',
    couponRatePercent: 0.7,
    markToMarketPercent: 65.34863,
    basketType: 'Single',
    underlierPerformancePercent: 65,
    listOfUnderliers: ['PDD', 'BABA', 'NIO'],
    activeUnderlier: 'BABA',
    activeUnderlierLevel: 89,
    protectionProximityLevelPercent: -2.4,
    protectionLevelPercent: 55.8,
    protectionType: 'Barrier',
    eventProximityPercent: 39,
    eventProximityIndicator: 'Below',
    eventLevelPercent: 45,
    notionalHoldingsSum: 1606000,
    intrinsicValue: 10000000,
    payoutAmount: 20000,
  },
  {
    eventId: '4',
    holdingId: '4',
    accountId: '20954',
    clientId: '45673',
    eventDate: '2022-10-12',
    cusip: '48133CQU9',
    isin: '48133CQU9',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Tech Autocall',
    eventType: 'Coupon Evaluation Date',
    couponRatePercent: 0.7,
    markToMarketPercent: 65.34863,
    basketType: 'Single',
    underlierPerformancePercent: 55,
    listOfUnderliers: ['AAPL', 'MSFT', 'AMZN'],
    activeUnderlier: 'AAPL',
    activeUnderlierLevel: 93,
    protectionProximityLevelPercent: 3.8,
    protectionLevelPercent: 69.9,
    protectionType: 'Barrier',
    eventProximityPercent: 41,
    eventProximityIndicator: 'Below',
    eventLevelPercent: 33,
    notionalHoldingsSum: 1789000,
    intrinsicValue: 2900000,
    payoutAmount: 12000,
  },
  {
    eventId: '5',
    holdingId: '5',
    accountId: '43914',
    clientId: '565673',
    eventDate: '2022-10-28',
    cusip: '61761JJ91',
    isin: '61761JJ91',
    issuer: 'Morgan Stanley',
    structureType: 'ARK ETF Autocall',
    eventType: 'Coupon Evaluation Date',
    couponRatePercent: 0.73,
    markToMarketPercent: 109.435,
    basketType: 'Single',
    underlierPerformancePercent: -85,
    listOfUnderliers: ['TSLA'],
    activeUnderlier: 'TSLA',
    activeUnderlierLevel: 93,
    protectionProximityLevelPercent: 3.8,
    protectionLevelPercent: 69.9,
    protectionType: 'Barrier',
    eventProximityPercent: 41,
    eventProximityIndicator: 'Abpve',
    eventLevelPercent: 43,
    notionalHoldingsSum: 989000,
    intrinsicValue: 8750000,
    payoutAmount: 32000,
  },
  {
    eventId: '6',
    holdingId: '6',
    accountId: '78914',
    clientId: '51673',
    eventDate: '2022-12-28',
    cusip: '61761JJ91',
    isin: '61761JJ91',
    issuer: 'Morgan Stanley',
    structureType: 'Pelosi Autocall',
    eventType: 'Coupon Evaluation Date',
    couponRatePercent: 0.88,
    markToMarketPercent: 109.435,
    basketType: 'Single',
    underlierPerformancePercent: -85,
    listOfUnderliers: ['NVDA', 'MSFT', 'AAPL'],
    activeUnderlier: 'MSFT',
    activeUnderlierLevel: 93,
    protectionProximityLevelPercent: 3.8,
    protectionLevelPercent: 69.9,
    protectionType: 'Barrier',
    eventProximityPercent: 88,
    eventProximityIndicator: 'Abpve',
    eventLevelPercent: 43,
    notionalHoldingsSum: 2523000,
    intrinsicValue: 342810,
    payoutAmount: 32108,
  },
];
