import { LifecycleProduct } from '../../productService/productServiceEndpoints';

export const mockLifecycleProductData: LifecycleProduct[] = [
  {
    productIdentifier: '06747NS88',
    issuer: 'Barclays Bank PLC',
    structureType: 'Point to Point Partially Principally Protected Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'INDU',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 3818000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 111.58,
    timeToMaturity: '4 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '22550J577',
    issuer: 'Deutsche Bank AG, London Branch',
    structureType: 'Capped Point to Point Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'JPM UN',
        source: 'BLOOMBERG',
        weight: 0.33333333333333337,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'GS UN',
        source: 'BLOOMBERG',
        weight: 0.33333333333333337,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'MS UN',
        source: 'BLOOMBERG',
        weight: 0.33333333333333337,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: 23978780,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 80.7,
    timeToMaturity: '3 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06747Q5E3',
    issuer: 'Barclays Bank PLC',
    structureType: 'Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: '20.19% Above',
    markToMarket: 119.23,
    timeToMaturity: '36 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48132PCT9',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Capped Dual Directional Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'EFA UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Equity Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 110.44,
    timeToMaturity: '1 Month',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '63305LHZ9',
    issuer: 'National Bank of Canada',
    structureType: 'Autocallable Contingent Interest Barrier Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPY UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'QQQ UQ',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'IWM UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Equity Basket',
    notional: 4530000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 86.02,
    timeToMaturity: '13 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48132WYL7',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Dual Directional Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 1000000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 90.07,
    timeToMaturity: '8 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '40434Y3Y1',
    issuer: 'HSBC Bank USA, National Assoc.',
    structureType: 'Cliquet CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 110.24,
    timeToMaturity: '6 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Coupon Evaluation Date',
      eventDate: '2022-08-23',
    },
  },
  {
    productIdentifier: '48126YU43',
    issuer: 'JPMorgan Chase Bank, N.A.',
    structureType: 'Autocallable Step Up Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'EFPLUS5D',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 42534000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 95.62,
    timeToMaturity: '32 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '45083AMT6',
    issuer: 'IBERIABANK',
    structureType: 'AutoCap CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'PG UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'GIS UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'QCOM UW',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'BA UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'KO UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'STX UW',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'TGT UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'VZ UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'OKE UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'OXY UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 99.440873725,
    timeToMaturity: '10 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Coupon Evaluation Date',
      eventDate: '2022-08-26',
    },
  },
  {
    productIdentifier: '48132RK82',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Capped Dual Directional Buffer Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'INDU',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 97.79,
    timeToMaturity: '< 1 Month',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06367YAX7',
    issuer: 'Bank of Montreal',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: undefined,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 4615000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 84.72,
    timeToMaturity: '60 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48132TBU9',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Dual Directional Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'ARKK UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Equity Basket',
    notional: 1000000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 42.92,
    timeToMaturity: '7 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '61773F2Y8',
    issuer: 'Morgan Stanley Finance LLC',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'INDU',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 4388000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '6.32% Above',
    markToMarket: 82.345,
    timeToMaturity: '36 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06748WLX9',
    issuer: 'Barclays Bank PLC',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 1276000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '4.92% Above',
    markToMarket: 82.54,
    timeToMaturity: '12 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Call Evaluation Date',
      eventDate: '2022-08-29',
    },
  },
  {
    productIdentifier: '48132RN30',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Capped Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'INDU',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 333000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 90.24,
    timeToMaturity: '8 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '45083AHK1',
    issuer: 'IBERIABANK',
    structureType: 'AutoCap CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'PPL UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'GM UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'DUK UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'LYB UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'VLO UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'F UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'VTR UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'CSCO UW',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'WELL UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'CVX UN',
        source: 'BLOOMBERG',
        weight: 0.1,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 100.015505985,
    timeToMaturity: '8 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06426XPL8',
    issuer: 'Bank of the West',
    structureType: 'All Up CD',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'F UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'VZ UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'PM UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'AAPL UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'DUK UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: 3576000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 101.62,
    timeToMaturity: '3 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '17329QJZ4',
    issuer: 'Citigroup Global Markets Holdings Inc.',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 2308000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '19.9% Above',
    markToMarket: undefined,
    timeToMaturity: '49 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06367YAP4',
    issuer: 'Bank of Montreal',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: undefined,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 5570000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 86.42,
    timeToMaturity: '47 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '09709UDK1',
    issuer: 'BofA Finance LLC',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 1536000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 90.32,
    timeToMaturity: '20 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '40438CLW9',
    issuer: 'HSBC Bank USA, Inc.',
    structureType: 'Capped Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: 0.15,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: 0.7,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'EFA UP',
        source: 'BLOOMBERG',
        weight: 0.15,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Equity Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'MATURED',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 117.24,
    timeToMaturity: 'Matured',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06747NYE8',
    issuer: 'Barclays Bank PLC',
    structureType: 'Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: 465000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 105.18,
    timeToMaturity: '5 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '38148DUQ5',
    issuer: 'Goldman Sachs Bank USA',
    structureType: 'Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'GSMBMA5S',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 111.19,
    timeToMaturity: '22 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06748WMC4',
    issuer: 'Barclays Bank PLC',
    structureType: 'Autocallable Fixed Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'XBI UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'ETF',
    notional: 642000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '19.04% Below',
    markToMarket: 56.82,
    timeToMaturity: '3 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '40435FSK4',
    issuer: 'HSBC Bank USA, Inc.',
    structureType: 'Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 124.88,
    timeToMaturity: '6 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '17326YF27',
    issuer: 'Citigroup Global Markets Holdings Inc.',
    structureType: 'Capped Point to Point Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 128.49,
    timeToMaturity: '18 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '17330AKS0',
    issuer: 'Citigroup Global Markets Holdings Inc.',
    structureType: 'Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'INDU',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 1269000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 88.11,
    timeToMaturity: '56 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48128HHZ4',
    issuer: 'JPMorgan Chase Bank, N.A.',
    structureType: 'Autocallable Step Up Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPECFR6P',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 1551000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 94.72,
    timeToMaturity: '20 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2349866199',
    issuer: 'Credit Suisse London Branch',
    structureType: 'Builder Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: 500000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 90.19,
    timeToMaturity: '23 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '40057EGG6',
    issuer: 'GS Finance Corp.',
    structureType: 'Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'INDU',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 106.793,
    timeToMaturity: '45 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '22550MUD9',
    issuer: 'Credit Suisse London Branch',
    structureType: 'Autocallable Contingent Interest Barrier Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'MS UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'WFC UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'GS UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'C UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: 5000000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 77.58,
    timeToMaturity: '47 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '61769HEP6',
    issuer: 'Morgan Stanley Finance LLC',
    structureType: 'Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: 1897000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 143.265,
    timeToMaturity: '23 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2108309365',
    issuer: 'Societe Generale SA',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 10000000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '43.46% Above',
    markToMarket: 96.34,
    timeToMaturity: '104 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Coupon Evaluation Date',
      eventDate: '2022-08-25',
    },
  },
  {
    productIdentifier: '06367YBM0',
    issuer: 'Bank of Montreal',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: undefined,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 8960000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 86.58,
    timeToMaturity: '62 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '61765QWY1',
    issuer: 'Morgan Stanley Bank, N.A.',
    structureType: 'Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPXT10UE',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 1354000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 111.585,
    timeToMaturity: '34 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2403580264',
    issuer: 'Credit Suisse AG, London Branch',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'OIH UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'ETF',
    notional: 3825000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 99.36,
    timeToMaturity: '40 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Coupon Evaluation Date',
      eventDate: '2022-08-23',
    },
  },
  {
    productIdentifier: '48133DBB5',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Dual Directional Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'MQUSTVA',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 2038000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 77.18,
    timeToMaturity: '55 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2327619206',
    issuer: 'BNP Paribas Issuance B.V.',
    structureType: 'Autocallable Step Up Dual Directional Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'NIO UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock',
    notional: 1000000,
    currency: 'USD',
    productStatus: 'MATURED',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 41.97,
    timeToMaturity: 'Matured',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06367YAY5',
    issuer: 'Bank of Montreal',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: undefined,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 11389000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 84.72,
    timeToMaturity: '60 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48126XBR5',
    issuer: 'JPMorgan Chase Bank, N.A.',
    structureType: 'Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'EFPLUS5D',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 20366000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 103.9,
    timeToMaturity: '13 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06368ESA1',
    issuer: 'Bank of Montreal',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 2340000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 87.8,
    timeToMaturity: '23 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2366923709',
    issuer: 'Barclays Bank PLC',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 3235000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 94.33,
    timeToMaturity: '38 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48126XEE1',
    issuer: 'JPMorgan Chase Bank, N.A.',
    structureType: 'Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'EFPLUS5D',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 104.35,
    timeToMaturity: '14 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06741W2K5',
    issuer: 'Barclays Bank PLC',
    structureType: 'Autocallable Contingent Interest Barrier Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'WYNN UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'UBER UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'AAL UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'ABNB UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: 1075000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '9.63% Below',
    markToMarket: 52.6,
    timeToMaturity: '24 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '06417X606',
    issuer: 'The Bank of Nova Scotia',
    structureType: 'Capped Point to Point Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'AAPL UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock',
    notional: 42184180,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 99.6,
    timeToMaturity: '2 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '17330F2H3',
    issuer: 'Citigroup Global Markets Holdings Inc.',
    structureType:
      'Fixed Interest Point to Point Fully Principally Protected Note',
    totalHoldings: 5,
    underlierList: [
      {
        name: undefined,
        symbol: 'CIISDA5N',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 23288000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth & Income',
    principalProximity: undefined,
    markToMarket: 100.92,
    timeToMaturity: '45 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '17294XZJ8',
    issuer: 'CitiBank, N.A.',
    structureType: 'Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'CIISDA5N',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 94.72,
    timeToMaturity: '15 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '38149JFQ8',
    issuer: 'Goldman Sachs Bank USA',
    structureType: 'Autocallable Step Up Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'GSMBMA5S',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 4714000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 94.37916,
    timeToMaturity: '50 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Call Evaluation Date',
      eventDate: '2022-08-29',
    },
  },
  {
    productIdentifier: '48126YED1',
    issuer: 'JPMorgan Chase Bank, N.A.',
    structureType: 'Point to Point CD',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'EFPLUS5D',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 104.38,
    timeToMaturity: '6 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '61770C384',
    issuer: 'Morgan Stanley Finance LLC',
    structureType: 'Autocallable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'QCOM UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock',
    notional: 12026550,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: undefined,
    timeToMaturity: '2 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2424947096',
    issuer: 'Morgan Stanley B.V.',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 8940000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 101.315,
    timeToMaturity: '31 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '40434AS67',
    issuer: 'HSBC Bank USA, N.A.',
    structureType: 'All Up CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'F UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'PM UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'MCD UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'WMT UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'BMY UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 99.93,
    timeToMaturity: '8 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48129MBL9',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Point to Point Barrier Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'EFA UP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Equity Basket',
    notional: undefined,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 115.34,
    timeToMaturity: '7 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '36260Y724',
    issuer: 'GS Finance Corp.',
    structureType: 'Autocallable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'DOCU UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock',
    notional: 23819810,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 99.9025,
    timeToMaturity: '23 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48133CNY4',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'ITM Digital Barrier Note',
    totalHoldings: 2,
    underlierList: [
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'RTY',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 886000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Digital',
    principalProximity: undefined,
    markToMarket: 91.48,
    timeToMaturity: '6 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48128FDV1',
    issuer: 'JPMorgan Chase Bank, N.A.',
    structureType: 'Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'EFPLUS5E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Cross Asset',
    notional: 2063000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 105.89,
    timeToMaturity: '11 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '48132RCQ1',
    issuer: 'JPMorgan Chase Financial Company LLC',
    structureType: 'Capped Point to Point Buffer Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: 496000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 100.19,
    timeToMaturity: '6 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '17294XVZ6',
    issuer: 'CitiBank, N.A.',
    structureType: 'All Up CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'NFLX UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'GOOGL UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'AAPL UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'AMZN UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'FB UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: 186000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 91.97,
    timeToMaturity: '50 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: 'XS2234883077',
    issuer: 'Barclays Bank PLC',
    structureType: 'Autocallable Fixed Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'BIDU UW',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'BABA UN',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'EDF FP',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Single Stock Basket',
    notional: 4000000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: '41.45% Below',
    markToMarket: 49.4,
    timeToMaturity: '18 Months',
    documents: undefined,
    nextEvent: {
      eventType: 'Call Evaluation Date',
      eventDate: '2022-08-25',
    },
  },
  {
    productIdentifier: '17329FYF5',
    issuer: 'Citigroup Global Markets Holdings Inc.',
    structureType: 'Issuer Callable Contingent Interest Barrier Note',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SX7E',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'NDX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index Basket',
    notional: 3607000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Income',
    principalProximity: undefined,
    markToMarket: 84.61,
    timeToMaturity: '71 Months',
    documents: undefined,
    nextEvent: undefined,
  },
  {
    productIdentifier: '61765QWV7',
    issuer: 'Morgan Stanley Bank, N.A.',
    structureType: 'Capped Point to Point CD',
    totalHoldings: 1,
    underlierList: [
      {
        name: undefined,
        symbol: 'SPX',
        source: 'BLOOMBERG',
        weight: undefined,
        underlierSource: 'Bloomberg',
        underlierSymbol: 'INDU',
      },
    ],
    activeUnderlier: undefined,
    assetClass: 'Index',
    notional: 3415000,
    currency: 'USD',
    productStatus: 'LIVE',
    returnType: 'Growth',
    principalProximity: undefined,
    markToMarket: 121.745,
    timeToMaturity: '46 Months',
    documents: undefined,
    nextEvent: undefined,
  },
];
