export const lumaPermissions = {
  access: {
    learningCenterModule: 'access.learning_center_module',
    lifecycleManagerAnnuities: 'access.lifecycle_manager_annuities',
  },
  creationHub: {
    deal: {
      client: 'creation_hub.deal.client',
      counterparty: 'creation_hub.deal.counterparty',
      edit: {
        issuerApproved: 'creation_hub.deal.detail.edit.issuer_approved',
      },
      issuer: 'creation_hub.deal.issuer',
      pag: 'creation_hub.deal.pag',
    },
    ubs: {
      adminAccess: 'creation_hub.ubs.admin_access',
      complianceTrainingComplete:
        'creation_hub.ubs.compliance_training_complete',
      createProceedToOffering: 'creation_hub.ubs.create_proceed_to_offering',
      productRequestQuotes: 'creation_hub.ubs.create_product_request_quotes',
      selectOfferingScope: 'creation_hub.ubs.select_offering_scope',
      selectRegistrationType: 'creation_hub.ubs.select_registration_type',
    },
  },
  form: {
    order: {
      adminFields: 'form.order.admin_fields',
      bookBuilding: {
        edit: 'form.order.book_building.edit',
      },
      liquidNetWorthOverride: 'form.order.liquid_net_worth_override',
      override: 'form.order.override',
      pmFields: 'form.order.pm_fields',
      repFields: 'form.order.rep_fields',
      salesFields: 'form.order.sales_fields',
    },
    redemptionEmail: 'form.redemption_email',
  },
  lifecycleMangager: {
    emailCenter: {
      tab: 'lifecyclemanager.email_center.tab',
    },
    eventConfirmations: {
      approver: 'lifecycle_manager.approver_event_confirmations',
      issuer: 'lifecycle_manager.issuer_event_confirmations',
    },
    productDetails: {
      orders: 'lifecyclemanager.product_details.orders',
    },
  },
  marketplace: {
    edit: { visibility: 'marketplace.edit.visibility' },
    enable: { overrideBuy: 'marketplace.enable.override.buy' },
  },
  menu: {
    admin: {
      adminGeneral: 'menu.admin',
      allMaturingProducts: 'menu.admin.all_maturing_products',
      clients: 'menu.admin.clients',
      companyRelationshipMapping: 'menu.admin.company_relationship_mapping',
      comparableStructureTypesConfiguration:
        'menu.admin.comparable_structure_types_configuration',
      complianceTrainingsExport: 'menu.admin.compliance_trainings_export',
      dailyOrdersExport: 'menu.admin.daily_orders_export',
      emailNotifications: 'menu.admin.order_email_notifications',
      fileUpload: 'menu.admin.file_upload',
      focusListVideo: 'menu.admin.focus_list_video',
      historicalEmails: 'menu.admin.historical_emails',
      markitingEmail: 'menu.admin.marketing_email_tracking_upload',
      pctClientPreferences: 'menu.admin.pct_client_preferences',
      pctIssuerPreferences: 'menu.admin.pct_issuer_preferences',
      productCenter: 'menu.admin.product_center',
      productMaintenance: {
        issuerConfirmationCreation:
          'menu.admin.product_maintenance.issuer_confirmation_creation',
        productEdit: 'menu.admin.product_maintenance.product_edit',
        productEntry: 'menu.admin.product_maintenance.product_entry',
        productMaintenanceGeneral: 'menu.admin.product_maintenance',
        reviewQueue: 'menu.admin.product_maintenance.review_queue',
        updateFinalValues: 'menu.admin.product_maintenance.update_final_values',
      },
      programIssuerMap: 'menu.admin.program_issuer_map',
      returnDescriptionTool: 'menu.admin.return_description_tool',
      users: 'menu.admin.users',
      webContent: 'menu.admin.web_content',
      wholesalerDefinition: 'menu.admin.wholesaler_definition',
      wholesalerMapping: 'menu.admin.wholesaler_mapping',
    },
    creationHub: {
      dataReporting: 'menu.creation_hub.data_reporting',
    },
    lifecycleManager: 'menu.lifecycle_manager',
    marketPlace: {
      annuity: 'menu.marketplace.annuity',
      buyButton: 'menu.marketplace.annuity.buy.button',
      configureButton: 'menu.marketplace.annuity.configure.button',
      orders: 'menu.marketplace.orders',
      settings: 'menu.marketplace.settings',
      v2: 'menu.marketplace.v2',
    },
    notificationCenter: 'menu.notification_center',
    pm: {
      configrationsKycRulesUpload: 'menu.pm_configurations_kyc_rules_upload',
      configurations: 'menu.pm_configurations',
      configurationsTomsExport: 'menu.pm_configurations_toms_export',
      wholeSalerMapping: 'menu.pm.wholesaler_mapping',
    },
    productMaintenance: {
      productEntrySuperaccess: 'product_maintenance.product_entry_superaccess',
      updateFinalValuesSuperaccess:
        'product_maintenance.update_final_values_superaccess',
    },
    secondaries: 'menu.secondaries',
  },
  secondaries: {
    rfq: {
      create: 'secondaries.rfq.create',
      respond: 'secondaries.rfq.respond',
    },
  },
};

// This is duplicated from libs/design-system/src/lib/components/GlobalNav/utils/widgetPermissions.ts
// We cannot import this type from here into the design-system
// As buildable/publishable libraries cannot import from other NX libraries
export enum WidgetPermissions {
  MenuCanViewLegacyDashboard = 'menu.can_view_legacy_dashboard',
  MenuCanViewLegacyNav = 'menu.can_view_legacy_nav',
  MenuLifecycleManager = 'menu.lifecycle_manager',
  MenuLifecycleManager2Beta = 'menu.lifecycle_manager_2_beta',
  MenuAdmin = 'menu.admin',
  MenuAdminUsers = 'menu.admin.users',
  MenuAdminReturnDescription = 'menu.admin.return_description_tool',
  MenuAdminWebContent = 'menu.admin.web_content',
  MenuAdminProgramIssuerMap = 'menu.admin.program_issuer_map',
  MenuAdminWebFocusListVideo = 'menu.admin.focus_list_video',
  MenuAdminMarketingEmailTrackingUpload = 'menu.admin.marketing_email_tracking_upload',
  MenuAdminAllMaturingProducts = 'menu.admin.all_maturing_products',
  MenuAdminComplianceTrainingsExport = 'menu.admin.compliance_trainings_export',
  MenuAdminCompanyRelationshipMapping = 'menu.admin.company_relationship_mapping',
  MenuAdminComparableStructureTypesConfiguration = 'menu.admin.comparable_structure_types_configuration',
  MenuAdminPCTIssuerPreferences = 'menu.admin.pct_issuer_preferences',
  MenuAdminPCTClientPreferences = 'menu.admin.pct_client_preferences',
  MenuAdminClients = 'menu.admin.clients',
  MenuAdminDailyOrdersExport = 'menu.admin.daily_orders_export',
  MenuAdminOrderEmailNotifications = 'menu.admin.order_email_notifications',
  MenuAdminHistoricalEmails = 'menu.admin.historical_emails',
  MenuAdminFileUpoad = 'menu.admin.file_upload',
  MenuAdminWholesalerDefinition = 'menu.admin.wholesaler_definition',
  MenuAdminWholesalerMapping = 'menu.admin.wholesaler_mapping',
  MenuCreationHubDataReporting = 'menu.creation_hub.data_reporting',
  MenuMarketplaceAnnuity = 'menu.marketplace.annuity',
  MenuMarketplaceAnnuityConfigureButton = 'menu.marketplace.annuity.configure.button',
  MenuMarketplaceAnnuityBuyButton = 'menu.marketplace.annuity.buy.button',
  MenuPmWholesalerMapping = 'menu.pm.wholesaler_mapping',
  MenuPmConfigurations = 'menu.pm_configurations',
  MenuPmConfigurationsKycRulesUpload = 'menu.pm_configurations_kyc_rules_upload', // todo: this is both kyc upload and validation upload
  MenuMarketplaceOrders = 'menu.marketplace.orders',
  MenuMarketplaceSettings = 'menu.marketplace.settings',
  MenuNotificationCenter = 'menu.notification_center',
  MenuSecondaries = 'menu.secondaries',
  SecondariesRFQCreate = 'secondaries.rfq.create',
  SecondariesRFQRespond = 'secondaries.rfq.respond',
  FormRedemptionEmail = 'form.redemption_email',
  CHDealDetailEditIssuerApproved = 'creation_hub.deal.detail.edit.issuer_approved',
  CHDealIssuer = 'creation_hub.deal.issuer',
  CHDealPag = 'creation_hub.deal.pag',
  CHDealCounterparty = 'creation_hub.deal.counterparty',
  CHDealClient = 'creation_hub.deal.client',
  AccessLearningCenter = 'access.learning_center_module',
  AccessLifecycleManagerAnnuities = 'access.lifecycle_manager_annuities',
  ProductCenter = 'menu.admin.product_center',
  MarketplaceRepFields = 'form.order.rep_fields',
  MarketplaceAdminFields = 'form.order.admin_fields',
  MarketplacePmFields = 'form.order.pm_fields',
  MarketplaceSalesFields = 'form.order.sales_fields',
  MarketplaceOverride = 'form.order.override',
  MarketplaceLnwOverride = 'form.order.liquid_net_worth_override',
  MarketplaceVisibility = 'marketplace.edit.visibility',
  MarketplaceOverrideBuy = 'marketplace.enable.override.buy',
  MarketplaceTomsExport = 'menu.pm_configurations_toms_export',
  MarketplaceBookBuildingEdit = 'form.order.book_building.edit',
  MarketplaceV2 = 'menu.marketplace.v2',
  ProductDetailsOrderTab = 'lifecyclemanager.product_details.orders',
  EmailCenterInbox = 'lifecyclemanager.email_center.tab',
  ProductMaintenance = 'menu.admin.product_maintenance',
  RangeToFinalAccess = 'menu.admin.product_maintenance.update_final_values',
  RangeToFinalSuperAccess = 'product_maintenance.update_final_values_superaccess',
  ProductMaintenanceProductEntry = 'menu.admin.product_maintenance.product_entry',
  ProductMaintenanceProductEntrySuper = 'product_maintenance.product_entry_superaccess',
  ProductMaintenanceProductEdit = 'menu.admin.product_maintenance.product_edit',
  ReviewQueueAccess = 'menu.admin.product_maintenance.review_queue',
  ICCAccess = 'menu.admin.product_maintenance.issuer_confirmation_creation',
  UBSAdmin = 'creation_hub.ubs.admin_access',
  UBSCreateProductRequestQuotes = 'creation_hub.ubs.create_product_request_quotes',
  UBSProceedToOffering = 'creation_hub.ubs.create_proceed_to_offering',
  UBSSelectOfferingScope = 'creation_hub.ubs.select_offering_scope',
  UBSSelectRegS = 'creation_hub.ubs.select_registration_type',
  UBSComplianceTrainingComplete = 'creation_hub.ubs.compliance_training_complete',
  LifecycleLimitedOrders = 'lifecycle_manager.limited_orders',
  CreationHubIssuer = 'menu.creation_hub_is_issuer',
  EventConfirmationsApprover = 'lifecycle_manager.approver_event_confirmations',
  EventConfirmationsIssuer = 'lifecycle_manager.issuer_event_confirmations',
}

const WidgetPermissionsValues = Object.values(WidgetPermissions);
type PermissionsArray = typeof WidgetPermissionsValues;
export const lumaPermissionsArray: PermissionsArray = [
  WidgetPermissions.MenuCanViewLegacyDashboard,
  WidgetPermissions.MenuCanViewLegacyNav,
  WidgetPermissions.MenuLifecycleManager,
  WidgetPermissions.MenuLifecycleManager2Beta,
  WidgetPermissions.MenuAdmin,
  WidgetPermissions.MenuAdminUsers,
  WidgetPermissions.MenuAdminReturnDescription,
  WidgetPermissions.MenuAdminWebContent,
  WidgetPermissions.MenuAdminProgramIssuerMap,
  WidgetPermissions.MenuAdminWebFocusListVideo,
  WidgetPermissions.MenuAdminMarketingEmailTrackingUpload,
  WidgetPermissions.MenuAdminAllMaturingProducts,
  WidgetPermissions.MenuAdminComplianceTrainingsExport,
  WidgetPermissions.MenuAdminCompanyRelationshipMapping,
  WidgetPermissions.MenuAdminComparableStructureTypesConfiguration,
  WidgetPermissions.MenuAdminPCTIssuerPreferences,
  WidgetPermissions.MenuAdminPCTClientPreferences,
  WidgetPermissions.MenuAdminClients,
  WidgetPermissions.MenuAdminDailyOrdersExport,
  WidgetPermissions.MenuAdminOrderEmailNotifications,
  WidgetPermissions.MenuAdminHistoricalEmails,
  WidgetPermissions.MenuAdminFileUpoad,
  WidgetPermissions.MenuAdminWholesalerDefinition,
  WidgetPermissions.MenuAdminWholesalerMapping,
  WidgetPermissions.MenuCreationHubDataReporting,
  WidgetPermissions.MenuMarketplaceAnnuity,
  WidgetPermissions.MenuMarketplaceAnnuityConfigureButton,
  WidgetPermissions.MenuMarketplaceAnnuityBuyButton,
  WidgetPermissions.MenuPmWholesalerMapping,
  WidgetPermissions.MenuPmConfigurations,
  WidgetPermissions.MenuPmConfigurationsKycRulesUpload,
  WidgetPermissions.MenuMarketplaceOrders,
  WidgetPermissions.MenuMarketplaceSettings,
  WidgetPermissions.MenuNotificationCenter,
  WidgetPermissions.MenuSecondaries,
  WidgetPermissions.SecondariesRFQCreate,
  WidgetPermissions.SecondariesRFQRespond,
  WidgetPermissions.FormRedemptionEmail,
  WidgetPermissions.CHDealDetailEditIssuerApproved,
  WidgetPermissions.CHDealIssuer,
  WidgetPermissions.CHDealPag,
  WidgetPermissions.CHDealCounterparty,
  WidgetPermissions.CHDealClient,
  WidgetPermissions.AccessLearningCenter,
  WidgetPermissions.AccessLifecycleManagerAnnuities,
  WidgetPermissions.ProductCenter,
  WidgetPermissions.MarketplaceRepFields,
  WidgetPermissions.MarketplaceAdminFields,
  WidgetPermissions.MarketplacePmFields,
  WidgetPermissions.MarketplaceSalesFields,
  WidgetPermissions.MarketplaceOverride,
  WidgetPermissions.MarketplaceLnwOverride,
  WidgetPermissions.MarketplaceVisibility,
  WidgetPermissions.MarketplaceOverrideBuy,
  WidgetPermissions.MarketplaceTomsExport,
  WidgetPermissions.MarketplaceBookBuildingEdit,
  WidgetPermissions.MarketplaceV2,
  WidgetPermissions.ProductDetailsOrderTab,
  WidgetPermissions.EmailCenterInbox,
  WidgetPermissions.ProductMaintenance,
  WidgetPermissions.RangeToFinalAccess,
  WidgetPermissions.RangeToFinalSuperAccess,
  WidgetPermissions.ProductMaintenanceProductEntry,
  WidgetPermissions.ProductMaintenanceProductEntrySuper,
  WidgetPermissions.ProductMaintenanceProductEdit,
  WidgetPermissions.ReviewQueueAccess,
  WidgetPermissions.ICCAccess,
  WidgetPermissions.UBSAdmin,
  WidgetPermissions.UBSCreateProductRequestQuotes,
  WidgetPermissions.UBSProceedToOffering,
  WidgetPermissions.UBSSelectOfferingScope,
  WidgetPermissions.UBSSelectRegS,
  WidgetPermissions.UBSComplianceTrainingComplete,
  WidgetPermissions.LifecycleLimitedOrders,
  WidgetPermissions.CreationHubIssuer,
  WidgetPermissions.EventConfirmationsApprover,
  WidgetPermissions.EventConfirmationsIssuer,
];
