import { CellClassParams, ColDef } from 'ag-grid-community';
import { colors } from '@luma-fe-workspace/design-system';

export const tableRowPlaceholderData = [
  {
    '#': 1,
    Order: 43323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 2,
    Order: 43323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 3,
    Order: 44323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 4,
    Order: 49823,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 5,
    Order: 43765,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 6,
    Order: 55501,
    Status: 'Active',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 7,
    Order: 45984,
    Status: 'Active',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 8,
    Order: 78743,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 9,
    Order: 55543,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 10,
    Order: 87654,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 1,
    Order: 43323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 2,
    Order: 43323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 3,
    Order: 44323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 4,
    Order: 49823,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 5,
    Order: 43765,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 6,
    Order: 55501,
    Status: 'Active',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 7,
    Order: 45984,
    Status: 'Active',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 8,
    Order: 78743,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 9,
    Order: 55543,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 10,
    Order: 87654,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 1,
    Order: 43323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 2,
    Order: 43323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 3,
    Order: 44323,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 4,
    Order: 49823,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 5,
    Order: 43765,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 6,
    Order: 55501,
    Status: 'Active',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 7,
    Order: 45984,
    Status: 'Active',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 8,
    Order: 78743,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 9,
    Order: 55543,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
  {
    '#': 10,
    Order: 87654,
    Status: 'Pending',
    Account: 'Default',
    'CUSIP/ISIN': '117043AE9',
    Description: 'Brunswick...',
    'Par Value': '100.00',
    Side: 'Bid Wanted',
    'Ask Qty': 100,
    'Due By': '1:05 PM',
    Price: 'Enter',
    'Good Until': '1:15 PM',
    Action: 'SUBMIT',
  },
];

export const tableColumnPlaceholderData: ColDef[] = [
  { field: '#', sortable: true, resizable: false },
  { field: 'Order', sortable: true },
  { field: 'Status', sortable: true },
  { field: 'Account', sortable: true },
  { field: 'CUSIP/ISIN' },
  { field: 'Description' },
  { field: 'Par Value' },
  { field: 'Side' },
  { field: 'Ask Qty' },
  { field: 'CUSIP/ISIN' },
  { field: 'Due By' },
  {
    field: 'Price',
    editable: true,
    singleClickEdit: true,

    cellStyle: (params: CellClassParams) => {
      if (params.value !== 'Enter') {
        return {
          color: `${colors.greyDarker}`,
          backgroundColor: `${colors.white}`,
          border: `0.0625rem solid ${colors.greyLight}`,
          outline: 'none',
        };
      } else {
        return {
          color: colors.greyLight,
          backgroundColor: `${colors.white}`,
          border: `0.0625rem solid ${colors.greyLight}`,
          outline: 'none',
        };
      }
    },
  },
  { field: 'Good Until' },
  { field: 'Action' },
];
